sudo: required
services:
  - docker

before_install:
  - docker build -t sandipbose/docker-react -f Dockerfile.dev .

script :
  - docker run -e CI=true sandipbose/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  region: "ap-south-1"
  app: "docker"
  env: "Docker-env-1"
  bucket_name: "elasticbeanstalk-ap-south-1-600183786481"
  bucket_path: "docker"
  on: 
    branch: master



